easy_admin:
    site_name: 'Backend Admin'
    entities:
#        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            list:
                max_results: 10
                fields:
                    - { property: 'name', label: 'Prénom' }
                    - { property: 'lastName', label: 'Nom' }
                    - { property: 'email', label: 'Email' }
        Post:
            class: App\Entity\Post
            list:
                max_results: 10
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Autheur' }
                    - { property: 'created_at', label: 'Créer le' }
        Comment:
            class: App\Entity\Comment
            list:
                max_results: 10
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Autheur' }
                    - { property: 'created_at', label: 'Créer le' }
