easy_admin:
    site_name: 'Backend Admin'
    entities:
#        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'name', label: 'Prénom' }
                    - { property: 'lastName', label: 'Nom' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'password', label: 'Mot de passe' }
                    - { property: 'isActive', label: 'Actif ?' }
                    - property: 'roles'
                      type: choice
                      type_options:
                          mapped: true
                          expanded: true
                          multiple: true
                          choices: {'Admin':'ROLE_ADMIN','Author':'ROLE_AUTHOR'}
            list:
                max_results: 10
                fields:
                    - { property: 'name', label: 'Prénom' }
                    - { property: 'lastName', label: 'Nom' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'isActive', label: 'Actif ?' }
                    - { property: 'isBlocked', label: 'Bloqué ?' }
                    - { property: 'roles', label: 'Role' }

        Post:
            class: App\Entity\Post
            list:
                max_results: 10
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'author', label: 'Autheur' }
                    - { property: 'created_at', label: 'Créer le' }
                    - { property: 'isPublished', label: 'Publié ?' }
            form:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'author', label: 'Autheur' }
                    - { property: 'isPublished', label: 'Publié ?' }

        Comment:
            class: App\Entity\Comment
            list:
                max_results: 10
                fields:
                    - { property: 'author', label: 'Autheur' }
                    - { property: 'created_at', label: 'Créer le' }
                    - { property: 'isDeleted', label: 'Supprimé ?' }
            form:
                fields:
                    - { property: 'author', label: 'Autheur' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'post', label: 'Post' }


